<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Enums\SocialPlatform;
use App\Models\Twitch;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

// todo this was generated by AI. Please dubble check it

final class LiveTwitchStreams extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:live-twitch-streams';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Check which Twitch streamers are currently live';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        // Record start time
        $startTime = microtime(true);

        $this->info('Starting LiveTwitchStreams check...');

        $totalStreams = 0;
        $liveStreams = 0;

        Twitch::query()->each(function (Twitch $twitch) use (&$totalStreams, &$liveStreams): void {
            $totalStreams++;
            $url = SocialPlatform::TWITCH->getBaseUrl().urlencode($twitch->name);
            // todo needs refactoring (using Twitch API)
            $html = Http::get($url)->body();

            $isLive = mb_strpos($html, '"isLiveBroadcast":true') !== false;

            if ($isLive) {
                $liveStreams++;
            }

            $twitch->update([
                'is_live' => $isLive,
            ]);
        });

        // Calculate execution time
        $endTime = microtime(true);
        $executionTime = round($endTime - $startTime, 2);

        $message = "LiveTwitchStreams completed in {$executionTime} seconds. Checked {$totalStreams} streams, found {$liveStreams} live.";

        // Output to console
        $this->info($message);

        // Log information
        Log::info($message);
    }
}
