<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Discord;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

//todo this was generated by AI. Please dubble check it

class DiscordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Count users and ensure we don't try to create more Discord accounts than there are users
        $userCount = User::count();
        $maxDiscordAccounts = min(50, $userCount);
        
        // Get users without Discord accounts, limited to reasonable number
        $users = User::doesntHave('discord')->inRandomOrder()->take($maxDiscordAccounts)->get();
        
        // Create Discord accounts for these users
        foreach ($users as $user) {
            Discord::factory()->forUser($user)->create();
        }
        
        // Make sure some specific Discord accounts are created
        $specificDiscordAccounts = [
            'admin_discord',
            'mod_discord',
            'support_discord',
            'help_discord',
            'game_master',
            'tournament_admin',
            'league_admin',
            'team_manager',
            'official_bot',
            'community_manager'
        ];
        
        foreach ($specificDiscordAccounts as $accountName) {
            // Check if this account name already exists
            if (!Discord::where('name', $accountName)->exists()) {
                // Find a user without a Discord account
                $user = User::doesntHave('discord')->inRandomOrder()->first();
                
                if ($user) {
                    $user->discord()->create([
                        'name' => $accountName,
                    ]);
                }
            }
        }
    }
} 