<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Federation;
use Illuminate\Database\Seeder;

// todo generated by AI double check it

final class FederationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->getEuropeanFederations() as $federation) {
            Federation::create($federation);
        }

        foreach ($this->getClubCompetitions() as $competition) {
            Federation::create($competition);
        }
    }

    /**
     * @return array[]
     */
    public function getEuropeanFederations(): array
    {
        $europeanFederations = [
            [
                'name' => 'PZPN', // Polish Football Association
                'type' => 'domestic',
                'region' => 'Poland',
            ],
            [
                'name' => 'DFB', // German Football Association
                'type' => 'domestic',
                'region' => 'Germany',
            ],
            [
                'name' => 'RFEF', // Spanish Football Federation
                'type' => 'domestic',
                'region' => 'Spain',
            ],
            [
                'name' => 'FIGC', // Italian Football Federation
                'type' => 'domestic',
                'region' => 'Italy',
            ],
            [
                'name' => 'FFF', // French Football Federation
                'type' => 'domestic',
                'region' => 'France',
            ],
            [
                'name' => 'FA', // English Football Association
                'type' => 'domestic',
                'region' => 'England',
            ],
        ];

        return $europeanFederations;
    }

    /**
     * @return array[]
     */
    public function getClubCompetitions(): array
    {
        $clubCompetitions = [
            [
                'name' => 'UEFA Champions League',
                'type' => 'continental',
                'region' => 'Europe',
            ],
            [
                'name' => 'UEFA Europa League',
                'type' => 'continental',
                'region' => 'Europe',
            ],
            [
                'name' => 'UEFA Conference League',
                'type' => 'continental',
                'region' => 'Europe',
            ],
        ];

        return $clubCompetitions;
    }
}
