<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Database\Factories\TwitchFactory;
use Illuminate\Database\Seeder;

// todo this was generated by AI. Please dubble check it

final class TwitchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::doesntHave('twitch')->inRandomOrder()->get();

        $twitchNames = collect(TwitchFactory::POPULAR_TWITCH_ACCOUNTS);

        $twitchNames->each(function (string $twitchName, int $index) use ($users) {
            $user = $users->get($index);
            if ($user) {
                $user->twitch()->create([
                    'name' => $twitchName,
                ]);
            }
        });
    }
}
