<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Discord;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

// todo this was generated by AI. Please dubble check it

/**
 * @extends Factory<Discord>
 */
final class DiscordFactory extends Factory
{
    /**
     * List of Discord username patterns
     */
    protected const DISCORD_PATTERNS = [
        '%s_discord',
        'discord_%s',
        '%s_gamer',
        'gaming_%s',
        '%s_player',
        '%s_pro',
        'pro_%s',
        '%s_gg',
        'gg_%s',
        '%s_tv',
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        static $discordNames = null;

        // Get random username without spaces
        $username = preg_replace('/\s+/', '', $this->faker->userName());

        // Apply a random pattern
        $pattern = $this->faker->randomElement(self::DISCORD_PATTERNS);
        $name = sprintf($pattern, $username);

        return [
            'name' => $name,
            'discordable_type' => User::class,
            'discordable_id' => User::factory(),
        ];
    }

    /**
     * Configure the factory to associate the Discord account with a specific user.
     */
    public function forUser(User $user): self|Factory
    {
        return $this->state(function (array $attributes) use ($user) {
            return [
                'discordable_id' => $user->id,
                'discordable_type' => User::class,
            ];
        });
    }
}
