<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// todo this was generated by AI. Please dubble check it

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('league_seasons', function (Blueprint $table) {
            $table->id();
            $table->foreignId('league_id')->constrained();
            $table->integer('season');
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
            $table->string('status'); // ['upcoming', 'active', 'completed']

            // A league can only have one season with a specific name
            $table->unique(['league_id', 'season']);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('league_seasons');
    }
};
