<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// todo this was generated by AI. Please dubble check it

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('league_season_team', function (Blueprint $table) {
            $table->id();
            $table->foreignId('team_id')->constrained();
            $table->foreignId('league_season_id')->constrained();

            // Team stats in this league season
            $table->integer('points')->default(0);
            $table->integer('played')->default(0);
            $table->integer('wins')->default(0);
            $table->integer('draws')->default(0);
            $table->integer('losses')->default(0);
            $table->integer('scored')->default(0);
            $table->integer('coincided')->default(0);

            $table->timestamps();

            // A team can only be in a specific league season once
            $table->unique(['team_id', 'league_season_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('league_season_team');
    }
};
